---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: angular-datepicker
  description: A datepicker for Angular.js
  tags:
    - javascript
spec:
  type: library
  lifecycle: production
